.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. title_qt test_title_qt
clean: FORCE
	$(MAKE) -C .. title_qt_clean test_title_qt_clean
check: FORCE
	$(MAKE) -C .. test_title_qt_check
title-qt title-qt.exe: FORCE
	 $(MAKE) -C .. title_qt
